// Code generated by mockery; DO NOT EDIT.
package mocks

import (
	"context"

	"backend_crudgo/users/models"

	"github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type.
type UserRepository struct {
	mock.Mock
}

// NewUserRepository creates a new instance of UserRepository. It also registers
// a testing interface on the mock and a cleanup function to assert the mock's expectations.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	m := &UserRepository{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

func (m *UserRepository) CreateUser(ctx context.Context, user *models.User) (*models.User, error) {
	args := m.Called(ctx, user)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*models.User), args.Error(1)
}

func (m *UserRepository) GetUser(ctx context.Context, id int64) (*models.User, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*models.User), args.Error(1)
}

func (m *UserRepository) GetUsers(ctx context.Context) ([]*models.User, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*models.User), args.Error(1)
}

func (m *UserRepository) LoginUser(ctx context.Context, userName, password string) (*models.LoginResponse, error) {
	args := m.Called(ctx, userName, password)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*models.LoginResponse), args.Error(1)
}
