// Code generated by mockery; DO NOT EDIT.
package mocks

import (
	"context"

	"backend_crudgo/domain/products/domain/model"

	"github.com/stretchr/testify/mock"
)

// ProductRepository is an autogenerated mock type for the ProductRepository type.
type ProductRepository struct {
	mock.Mock
}

// NewProductRepository creates a new instance of ProductRepository. It also registers
// a testing interface on the mock and a cleanup function to assert the mock's expectations.
func NewProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRepository {
	m := &ProductRepository{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

func (m *ProductRepository) CreateProduct(ctx context.Context, product *model.Product) (*model.Product, error) {
	args := m.Called(ctx, product)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*model.Product), args.Error(1)
}

func (m *ProductRepository) GetProduct(ctx context.Context, id int64) (*model.Product, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*model.Product), args.Error(1)
}

func (m *ProductRepository) GetProducts(ctx context.Context) ([]*model.Product, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*model.Product), args.Error(1)
}

func (m *ProductRepository) UpdateProduct(ctx context.Context, id int64, product *model.Product) error {
	args := m.Called(ctx, id, product)
	return args.Error(0)
}

func (m *ProductRepository) DeleteProduct(ctx context.Context, id int64) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}
