// Code generated by mockery; DO NOT EDIT.
package mocks

import (
	"context"

	"backend_crudgo/domain/users/domain/model"

	"github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type.
type UserService struct {
	mock.Mock
}

// NewUserService creates a new instance of UserService. It also registers
// a testing interface on the mock and a cleanup function to assert the mock's expectations.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	m := &UserService{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

func (m *UserService) CreateUser(ctx context.Context, user *model.User) (*model.User, error) {
	args := m.Called(ctx, user)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*model.User), args.Error(1)
}

func (m *UserService) LoginUser(ctx context.Context, userName, password string) (*model.LoginResponse, error) {
	args := m.Called(ctx, userName, password)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*model.LoginResponse), args.Error(1)
}

func (m *UserService) GetUser(ctx context.Context, id int64) (*model.User, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*model.User), args.Error(1)
}

func (m *UserService) GetUsers(ctx context.Context) ([]*model.User, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*model.User), args.Error(1)
}
